### ISSUE TITLE
Cant log in with default username and password

### ISSUE THREAD

**Issue by khinze** [slafs/sentry-docker#14]
I followed all the staps in the quick start. I cant seem to login with admin admin. Did the default username and password change?

**Comment by slafs** [comment]
Nope. ``admin/admin`` should work just fine. Maybe you can show your logs while running your container? And paste the command that you're using to launch it.

**Comment by khinze** [comment]
sudo docker run -d --name=sentry --volume=/tmp/sentry:/data -p 80:9000 -e SECRET_KEY=(My Own key here) -e SENTRY_URL_PREFIX=http://sentry.myurl.co.za slafs/sentry.

I'll try find logs now.

**Comment by khinze** [comment]
[WARNING] /usr/local/lib/python2.7/site-packages/sentry/web/decorators.py:45: DeprecationWarning: sentry.web.frontend.projects.rules.create_or_edit_rule is used deprecated @has_access
  DeprecationWarning)

[WARNING] /usr/local/lib/python2.7/site-packages/sentry/web/decorators.py:45: DeprecationWarning: sentry.web.frontend.projects.rules.remove_rule is used deprecated @has_access
  DeprecationWarning)

[WARNING] /usr/local/lib/python2.7/site-packages/sentry/web/decorators.py:45: DeprecationWarning: sentry.web.frontend.projects.tags.manage_project_tags is used deprecated @has_access
  DeprecationWarning)

This was in my /tmp/sentry/gunicorn error log

**Comment by khinze** [comment]
" - - [24/Feb/2015:15:46:34] "POST /login/ HTTP/1.1" 200 - "http://sentry.*.co.za/login/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"
" - - [24/Feb/2015:15:46:39] "GET /_static/sentry/dist/vendor-backbone.min.js HTTP/1.1" 200 35522 "http://sentry.*.co.za/login/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"
" - - [24/Feb/2015:15:46:41] "GET /_static/sentry/dist/vendor-misc.min.js HTTP/1.1" 200 100791 "http://sentry.*.co.za/login/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"
" - - [24/Feb/2015:15:46:41] "GET /_static/sentry/dist/vendor-bootstrap.min.js HTTP/1.1" 200 43448 "http://sentry.*.co.za/login/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35

**Comment by khinze** [comment]
All seems fine to me.

**Comment by slafs** [comment]
You should also show me your logs from the container itself. Something like ``docker logs sentry`` should be good.

**Comment by khinze** [comment]
Slafs, I ended up deleted my virtual server and just re-installing it again and it worked fine. I mustve not done something right the first time around. 

Thanks.

**Comment by slafs** [comment]
Great! Glad you sorted it out.
