### ISSUE TITLE
Allow passing SCRIPT_NAME / FORCE_SCRIPT_NAME?

### ISSUE THREAD

**Issue by aldanor** [slafs/sentry-docker#19]
I'm trying to run sentry-docker behind a reverse proxy (nginx) which mounts it on a subpath so it's accessible at `http://my.host/sentry`. However, the auth redirects to `http://my.host/auth/login` instead of `http://my.host/sentry/auth/login` which obviously doesn't work; that is, evern with url prefix set correctly.

It seems like passing `FORCE_SCRIPT_NAME` and optionally `SCRIPT_NAME` (in addition to `SENTRY_URL_PREFIX`) may be able to solve this: getsentry/sentry#392, so it makes sense to support passing these values through environment variables.

**Comment by slafs** [comment]
This is probably something we could support inside this image, but as David Cramer (the author of Sentry) stated in https://github.com/getsentry/sentry/issues/392#issuecomment-69843155 there's no guarantee that this will work. Feel free to open a pull request.
