### ISSUE TITLE
Redis InvalidCacheBackendError

### ISSUE THREAD

**Issue by FatNarwhal** [slafs/sentry-docker#26]
I'm getting an error as I build the container with redis (used the same command specified in readme, `docker run -d --name=sentry --volume=/tmp/sentry:/data -p 80:9000 --env-file=environment --link=postgres_container:postgresdb --link=redis_container:redis slafs/sentry`):

The command works fine, I am able to log into sentry from browser, but once I include CACHE_URL=hiredis://redis:6379/2/ in the environment file to use redis and rebuild the container, I get this in the resulting container's logs:

`InvalidCacheBackendError: Could not find backend 'redis_cache.cache.RedisCache': Error importing module redis_cache.cache: "No module named redis_cache.cache"`

**Comment by slafs** [comment]
Thanks for the report. Will try to take a closer look at this. 

What do you mean by "rebuild the container"? Are you preparing your own image as in [here](https://github.com/slafs/sentry-docker#extending-the-image) or you just stop the container and run another one?

**Comment by FatNarwhal** [comment]
Thanks for replying! Sorry for the confusion. What I meant was that I was stopping the container and running another.

**Comment by slafs** [comment]
This is because ``django-redis`` since version 4.0 has dropped ``redis_cache`` as a valid package name (see niwinz/django-redis#143) and django-cache-url doesn't support the new naming from ``django-redis>=4.0`` yet. I guess I will revert to an older version of django-redis for now.

**Comment by slafs** [comment]
build just finished on docker hub. Can you confirm that the problem is gone?

**Comment by FatNarwhal** [comment]
The problem is gone. Thanks!

**Comment by slafs** [comment]
No problem. I opened a PR for supporting the new syntax and path ghickman/django-cache-url#23
