### ISSUE TITLE
AWS SES email not working

### ISSUE THREAD

**Issue by robertdolca** [slafs/sentry-docker#29]
I am trying to use this docker template. Everything works beside the email. I configured the user, password, host, server email and TLS. When I am trying to send a test email it does not report any error.

The downside is that there is nothing in the log. Could you export the app logs? Is it ok to add a SSH server in the container?

Thanks,
Robert

**Comment by slafs** [comment]
Hey. I don't know much about AWS SES but I guess you should also set ``SENTRY_EMAIL_PORT``. Also after some brief skimming on StackOverflow it seems that people had problems with sending emails in Django via AWS SES and they use some various 3rd party libraries for this task. Note that current version of Sentry uses an older version of Django i.e. 1.6.11

**Comment by robertdolca** [comment]
I understand. The issue is that I have no access in container to debug this. How should I fix that?

**Comment by slafs** [comment]
Oh and it's totally not OK to add a SSH server into the container and I would avoid this as much as I could if I were you. Maybe ``docker exec <container> bash`` will help.

**Comment by robertdolca** [comment]
My settings look like this. I am using the same credentials elsewhere and everything works.

SENTRY_EMAIL_HOST=email-smtp.eu-west-1.amazonaws.com
SENTRY_EMAIL_HOST_USER=<user>
SENTRY_EMAIL_HOST_PASSWORD=<password>
SENTRY_EMAIL_USE_TLS=1
SENTRY_SERVER_EMAIL=<authorized email>
SENTRY_EMAIL_PORT=25

**Comment by robertdolca** [comment]
I was seting the SMTP credentials but I didn't specify the backend at all.
After adding SENTRY_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend everything worked.

Thanks @slafs
