### ISSUE TITLE
Do you plan to support docker-compose?

### ISSUE THREAD

**Issue by yellowiscool** [slafs/sentry-docker#31]
Hello,

Thank you for this docker image. It works perfectly.

Do you plan to add a docker-compose file to facilitate even more the deployment?

**Comment by slafs** [comment]
Hey!

I'm not sure what do you mean by "supporting docker-compose"? 

I think there are so many use cases for configuring this image that I don't think it's reasonable to have an "official" `docker-compose.yml` file. You can see `tests` directory to see how this image can be used with `docker-compose`.

**Comment by yellowiscool** [comment]
Ah thank you. I was looking for an example `docker-compose.yml` file but you already have them in the `tests` folder.
