### ISSUE TITLE
"Background workers haven't checked in recently"

### ISSUE THREAD

**Issue by mbajur** [slafs/sentry-docker#32]
Hello!
I'm trying to use this docker image (i'm a total newbie, that's my first time trying to use docker for anything). Here is what i did so far:

* `docker pull slafs/sentry`
* `sudo docker run -d --name=sentry --volume=/tmp/sentry:/data -p 80:9000 -e SECRET_KEY=randomvalue -e SENTRY_URL_PREFIX=http://my.domain.com slafs/sentry`

There is no any error report in `docker logs` (just a lot of deprecation warnings) and i'm able to access sentry web panel but there is a red notice on each page saying:

    Background workers haven't checked in recently. This can mean an issue with your configuration or a serious backlog in tasks.

The most recent not-warning message in `docker logs` says 

    Running service: 'http'

and after that, there is just that: https://gist.github.com/mbajur/57cd8c6979bcb220107e
Have you any idea what possibly gone wrong in here? Am i missing something?

Thanks in advance!

**Comment by slafs** [comment]
Hey! You have to run (at least) one more process/container with `celery worker -B`. Take a look at [README](https://github.com/slafs/sentry-docker#celery-with-redis-and-postgres) and Sentry docs. You'll figure it out ;). 
Also you might want to look at this example [`docker-compose.yml`](https://github.com/slafs/sentry-docker/blob/master/tests/simple_services/docker-compose.yml) file.

**Comment by mbajur** [comment]
Thanks for your reply! I'm not sure if i understand it all well but - running `docker-compose -f docker-compose.yml -d` should start a deamonized containers and sentry should be ready to use, am i right?

If so, the last log line of `simpleservices_sentryweb` is `Running service: 'http'`and it seems to be frozen + `simpleservices_celery` dies after few seconds + web interface is not working for me.

**Comment by slafs** [comment]
You should run compose from a repository root directory but those are for testing purposes mainly so that really doesn't matter. I just wanted to show you example configuration fro running Sentry with Celery.

Let's step back a little. Do you know how to run Sentry without Docker? The README here shouldn't replace Sentry docs. Go read both and I'm sure you'll get it eventually.

**Comment by offlinehacker** [comment]
I'm having same issue, even when i'm running celery worker. It looks like celery is stuck in this state. Is this possible?

**Comment by gzcf** [comment]
I had same issue. This is my solution.
To eliminate this error report, add these environment variables:

```
## some other  environment variables...

## celery
CELERY_ALWAYS_EAGER=False
SENTRY_BROKER_URL=redis://127.0.0.1:6379/1

## cache
CACHE_URL=hiredis://127.0.0.1:6379/2
```

and ***start celery workers***. Also you should run sentry-docker with linked redis container. 
I didn't use dockerize redis. So you should replace `127.0.0.1` with your redis container alias. Hope this can help you.

**Comment by slafs** [comment]
right, `CELERY_ALWAYS_EAGER=False` is very important . Also see #35. TL;DR - pull a new image version

**Comment by jpatel3** [comment]
I am running into the similar issue in my local. Not sure which configuration is causing it. As Redis and sentry both seems to be running fine.

**Comment by slafs** [comment]
As of bb038d2fb8691d6 you can avoid setting `C_FORCE_ROOT` by configuring `CELERY_RESULT_SERIALIZER`, `CELERY_TASK_SERIALIZER` and `CELERY_ACCEPT_CONTENT` to `json`.

**Comment by natsu90** [comment]
Hi @mbajur, I have exactly same error like yours, so how you resolve this? I'm also new in Docker and Sentry.

**Comment by mbajur** [comment]
Actually i stopped using it :) However, i'm gonna try it again in upcoming
days/weeks so i'll let you know.

**Comment by natsu90** [comment]
Hey @mbajur I tried this and it works, https://github.com/slafs/sentry-docker/issues/35#issuecomment-162562504. Good luck.

**Comment by adamlc** [comment]
Weirdly I've just got this issue upgrading to Sentry 8.0.6, the config worked before and it seems to be working with 8.0.6 but it is displaying the message in red. Everything else seems to be working otherwise, very odd!

**Comment by jpatel3** [comment]
@adamlc It may be because of some dependency version mismatch?
