### ISSUE TITLE
Background workers haven't checked in recently...

### ISSUE THREAD

**Issue by tarasinf** [slafs/sentry-docker#35]
Hi, 
I tried to install Sentry to server using your sentry-docker. I got some troubles with it. I hope, you'll help me, you are my last chans. Theare is a list of my command and errors. 

Thanks. 
Pre-cleared folder /tmp/
****************************
docker run -d --name=postgres_container postgres

docker run -d --name=redis_container redis

docker run -d --name=sentry_celery_worker --link=redis_container:redis --link=postgres_container:postgresdb --volume=/tmp/sentry:/data --env-file=environment slafs/sentry celery worker -B

docker run -d --name=sentry --volume=/tmp/sentry:/data -p 80:9000 --env-file=environment --link=postgres_container:postgresdb --link=redis_container:redis slafs/sentry
****************************

When I entered to url sentry I got this red error: "Background workers haven't checked in recently. This can mean an issue with your configuration or a serious backlog in tasks."

In 'docker logs sentry_celery_worker' I got the next error:

****************************
"[2015-10-01 12:40:11,224: WARNING/Worker-2] /usr/local/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: OperationalError('no such table: sentry_project',):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 125, in handle_failure
    einfo=einfo)
  File "/usr/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/celery/__init__.py", line 33, in process_failure_signal
    'kwargs': kwargs,
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 676, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 39, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 157, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 521, in capture
    self.send(**data)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 50, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 209, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: sentry_project

  exc, exc_info.traceback)))
" 
****************************

When I was trying to send test email from admin I got red error: "Connection unexpectedly closed: timed out".

**Comment by slafs** [comment]
It would be useful to see what you have in your `environment` file that you use to run sentry's http service and celery workers.

**Comment by tarasinf** [comment]
### required settings

SENTRY_URL_PREFIX=http://**.**.**.*
SECRET_KEY=randomvalue

### other settings
### (https://docs.djangoproject.com/en/1.5/ref/settings/)
### (http://sentry.readthedocs.org/en/latest/config/index.html)

## celery
CELERY_ALWAYS_EAGER=False
SENTRY_BROKER_URL=redis://redis:6379/1

## make everything "public" (readable by all logged in users)
#SENTRY_PUBLIC=True

## postgres DB
DATABASE_URL=postgres://postgres:@postgresdb/postgres

## cache
#CACHE_URL=hiredis://redis:6379/2

## redis buffers
#SENTRY_USE_REDIS_BUFFERS=True
#SENTRY_REDIS_BUFFERS=redis1:6379,redis2:6379

## redis time-series storage
#SENTRY_USE_REDIS_TSDB=True
#SENTRY_REDIS_TSDBS=redis1:6379,redis2:6379

## initial superuser
SENTRY_ADMIN_USERNAME=t******f
SENTRY_ADMIN_PASSWORD=t******f
SENTRY_ADMIN_EMAIL=t************3@gmail.com

## email settings
SENTRY_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
SENTRY_EMAIL_HOST=smtp.sendgrid.net
SENTRY_EMAIL_HOST_PASSWORD=M*****5
SENTRY_EMAIL_HOST_USER=t*******8
SENTRY_EMAIL_PORT=465
SENTRY_EMAIL_USE_TLS=False
SENTRY_SERVER_EMAIL=t*****m

## social auth
#TWITTER_CONSUMER_KEY=""
#TWITTER_CONSUMER_SECRET=""
#FACEBOOK_APP_ID=""
#FACEBOOK_API_SECRET=""
#GOOGLE_OAUTH2_CLIENT_ID=""
#GOOGLE_OAUTH2_CLIENT_SECRET=""
#GITHUB_APP_ID=""
#GITHUB_API_SECRET=""
#TRELLO_API_KEY=""
#TRELLO_API_SECRET=""
#BITBUCKET_CONSUMER_KEY=""
#BITBUCKET_CONSUMER_SECRET=""


## LDAP (https://pythonhosted.org/django-auth-ldap/reference.html)
#SENTRY_USE_LDAP=True
#LDAP_SERVER=ldap://localhost
#LDAP_BIND_DN=cn=admin,dc=example,dc=com
#LDAP_BIND_PASSWORD=ldapadminpassword
#LDAP_USER_DN=REQUIRED! e.g. ou=users,dc=example,dc=com
#LDAP_USER_FILTER=(&(objectClass=inetOrgPerson)(cn=%(user)s))
#LDAP_GROUP_DN=ou=django,ou=groups,dc=example,dc=com
#LDAP_GROUP_FILTER=(objectClass=groupOfUniqueNames)
#LDAP_REQUIRE_GROUP=cn=enabled,ou=django,ou=groups,dc=example,dc=com
#LDAP_DENY_GROUP=cn=disabled,ou=django,ou=groups,dc=example,dc=com
#LDAP_GROUP_TYPE='groupOfUniqueNames'
#LDAP_MAP_FIRST_NAME=givenName
#LDAP_MAP_LAST_NAME=sn
#LDAP_MAP_MAIL=mail
#LDAP_GROUP_ACTIVE=cn=active,ou=django,ou=groups,dc=example,dc=com
#LDAP_GROUP_STAFF=cn=staff,ou=django,ou=groups,dc=example,dc=com
#LDAP_GROUP_SUPERUSER=cn=superuser,ou=django,ou=groups,dc=example,dc=com
#LDAP_FIND_GROUP_PERMS=False
#LDAP_CACHE_GROUPS=True
#LDAP_GROUP_CACHE_TIMEOUT=3600

## REMOTE_USER (https://docs.djangoproject.com/en/stable/howto/auth-remote-user/)
#SENTRY_USE_REMOTE_USER=True
#AUTH_REMOTE_USER_HEADER=HTTP_X_SSO_USERNAME

## others
#SENTRY_ALLOW_REGISTRATION=True
#SENTRY_DATA_DIR=/data
#SENTRY_SCRIPTS_DIR=/conf
#SENTRY_BEACON=False

## bootstraping a project
#SENTRY_INITIAL_TEAM=testteam
#SENTRY_INITIAL_PROJECT=testproject
#SENTRY_INITIAL_KEY=public:secret
#SENTRY_INITIAL_DOMAINS="domain.com *.domain.com"
#SENTRY_DOCKER_DO_DB_CHECK=yes

## Proxy & SSL
#SENTRY_SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
#SENTRY_USE_X_FORWARDED_HOST=True

## allows JavaScript clients to submit cross-domain error reports.
#SENTRY_ALLOW_ORIGIN="http://foo.example"



C_FORCE_ROOT=1

**Comment by tarasinf** [comment]
Hi, can you write which version of Docker image postgres and redis do you use in sentry for successful running?

**Comment by slafs** [comment]
So. Try to run worker after you run `http` service. I notice some minor problems with this. I updated run script to not emit any errors so try to pull a newer image version. 

If that doesn't help try to enable `CACHE_URL`

**Comment by slimadvies** [comment]
This works:
```
docker run -d --name=postgres_container postgres
docker run -d --name=redis_container redis
docker run -d --name=sentry --volume=/tmp/sentry:/data -p 80:9000 --env-file=environment --link=postgres_container:postgres --link=redis_container:redis slafs/sentry
docker run -d --name=sentry_celery_worker_beat --link=redis_container:redis --link=postgres_container:postgres --volume=/tmp/sentry:/data --env-file=environment -e C_FORCE_ROOT=1 slafs/sentry celery worker -B
docker run -d --name=sentry_celery_worker1 --link=redis_container:redis --link=postgres_container:postgres --volume=/tmp/sentry:/data --env-file=environment -e C_FORCE_ROOT=1 slafs/sentry celery worker
```

The difference is `-e C_FORCE_ROOT=1` for celery workers

**Comment by Andrii-D** [comment]
You can use Docker-Compose to orchestrate all of this containers.
All you need is two files:  
1. docker-compose.yml
2. env.conf (all your environments)  

Here is a __docker-compose.yml__ file:
```
redis:
  image: redis:latest
  command: redis-server --appendonly yes
  container_name: redis
postgres:
  image: postgres
  container_name: postgres
sentry:
  image: slafs/sentry
  ports:
    - "80:9000"
  env_file: ./env.conf
  volumes:
    - /tmp/sentry:/data
  links:
    - redis
    - postgres

sentry_celery_worker:
  command: celery worker -l info
  image: slafs/sentry
  env_file: ./env.conf
  environment:
    C_FORCE_ROOT: 1
  volumes:
    - /tmp/sentry:/data
  links:
    - redis
    - postgres

sentry_celery_worker_beat:
  command: celery worker -B -l info
  image: slafs/sentry
  env_file: ./env.conf
  environment:
    C_FORCE_ROOT: 1
  volumes:
    - /tmp/sentry:/data
  links:
    - redis
    - postgres
```

And here is an __env.conf__ file:
```
SENTRY_URL_PREFIX=http://yourdomain.com
SECRET_KEY=randomstring

CELERY_ALWAYS_EAGER=False
SENTRY_BROKER_URL=redis://redis:6379/1

# make everything "public" (readable by all logged in users)
#SENTRY_PUBLIC=True

# postgres DB
DATABASE_URL=postgres://postgres:@postgres/postgres

# cache
CACHE_URL=hiredis://redis:6379/2

# initial superuser
SENTRY_ADMIN_USERNAME=username
SENTRY_ADMIN_PASSWORD=password
SENTRY_ADMIN_EMAIL=email

# email settings
SENTRY_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
SENTRY_EMAIL_HOST=host
SENTRY_EMAIL_HOST_PASSWORD=pass
SENTRY_EMAIL_HOST_USER=user
```
So you just need to run:
`docker-compose up -d`
and then:
`docker-compose restart`

**Comment by slafs** [comment]
As of bb038d2fb8691d6 you can avoid setting `C_FORCE_ROOT` by configuring `CELERY_RESULT_SERIALIZER`, `CELERY_TASK_SERIALIZER` and `CELERY_ACCEPT_CONTENT` to `json`.

**Comment by natsu90** [comment]
Thanks @Andrii-D that works
