### ISSUE TITLE
Celery ignoring BROKER_URL

### ISSUE THREAD

**Issue by skenmy** [slafs/sentry-docker#36]
It seems that running `celery worker -B` as the starting command for the container as per the instructions doesn't honor the SENTRY_BROKER_URL environment variable.

```[2015-10-09 12:51:28,719: ERROR/Beat] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2015-10-09 12:52:00,709: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...```

As such I am unable to start any workers.

**Comment by skenmy** [comment]
Interestingly, running `docker exec worker-container sentry --config=/conf/sentry_docker_conf.py celery worker -B`, where `worker-container` is the running container giving the connection error, succeeds!

**Comment by slafs** [comment]
what's the value of your `SENTRY_BROKER_URL` env var?

**Comment by slafs** [comment]
maybe your problem is similar to https://github.com/slafs/sentry-docker/issues/39#issuecomment-149463472 ?

**Comment by robertdolca** [comment]
I am having the same issue and I don't have tailing slashes. Is currently another issue that is causing this?

**Comment by robertdolca** [comment]
@slafs do you have any sugestion how I could investigate this?

**Comment by slafs** [comment]
well, @robertdolca first of all open a seperate issue, second of all let us look at some of your logs to actually be able to help
