### ISSUE TITLE
Upgrade to v8

### ISSUE THREAD

**Issue by ZucchiniZe** [slafs/sentry-docker#40]
Sentry released sentry 8 recently, I would love to be able to easily deploy it myself.

http://blog.getsentry.com/2015/10/08/sentry-8-is-here.html

**Comment by slafs** [comment]
There's no `sentry==8.0` on PyPi, yet. Only hosted version of sentry has 8.0 for now.

**Comment by andrew-dixon** [comment]
@slafs Sentry 8 is now on PyPi - https://pypi.python.org/pypi/sentry/8.0.0rc1

**Comment by slafs** [comment]
thanks, I think I'm going to wait for a stable release.

**Comment by andrew-dixon** [comment]
@slafs Sentry 8 final is now available on PyPi - https://pypi.python.org/pypi/sentry/8.0.0
