### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by koszikot** [slafs/sentry-docker#43]
Hi, 

how can I set log level of sentry, so it doesn't throw 3244657 deprecation warnings on each request? I'm using latest images and each request throws tons lines like this:

```bash
sentry_1 | [WARNING] /usr/local/lib/python2.7/site-packages/sentry/web/decorators.py:45: DeprecationWarning: sentry.web.frontend.projects.rules.list_rules is used deprecated @has_access
sentry_1 |   DeprecationWarning)
```

**Comment by slafs** [comment]
Yeah, that can be annoying, but sorry, that's how sentry works for now. It uses some deprecated features (although I think they are internal). You can ignore warnings by adding env var `PYTHONWARNINGS=ignore` to your container.

See 7976785.
Also see https://docs.python.org/2/library/warnings.html and https://docs.python.org/2/using/cmdline.html#envvar-PYTHONWARNINGS
