### ISSUE TITLE
env variable name mistake

### ISSUE THREAD

**Issue by lvyaojia** [slafs/sentry-docker#45]
In this table:
https://github.com/slafs/sentry-docker/blob/master/README.md#available-environment-variables 

`SENTRY_USE_REDIS_BUFFER` should be `SENTRY_USE_REDIS_BUFFERS`, according to the config file (https://github.com/slafs/sentry-docker/blob/master/sentry_docker_conf.py#L80).

thanks

**Comment by slafs** [comment]
Thanks. You wanna make a PR?

**Comment by lvyaojia** [comment]
Aha, just one character, no need to make a PR, thanks.

**Comment by onlydole** [comment]
@slafs This issue can be closed

**Comment by slafs** [comment]
thx
