### ISSUE TITLE
groupOfNames LDAP Option

### ISSUE THREAD

**Issue by TheSavior** [slafs/sentry-docker#53]
We want to specify groupOfNames here: https://github.com/slafs/sentry-docker/blob/master/sentry_docker_conf.py#L212

Is there any way to do that without a new version of `sentry-docker`?

**Comment by slafs** [comment]
Sorry, LDAP support is grim in this image. I'm not going to add another condition for now.
You can try to [extend this image](https://github.com/slafs/sentry-docker#extending-the-image) and build your own with any modifications you want.
